version: "3.9"

networks:
  internal:

services:
  caddy:
    image: saile2204/caddy-proxy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "2019:2019"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - ddns
    networks:
      - caddy
    cgroup: host
    deploy:
      labels: # Global options
        caddy.email: eliasstepanik@web.de
  
  server:
    build:
      context: .
      dockerfile: ./AutoProxy.Server/Dockerfile
    image: saile2204/autoproxy-server:latest
    tty: true
    networks:
      - internal
  
  ddns-updater:
    build:
      context: .
      dockerfile: ./AutoProxy.DdnsUpdater/Dockerfile
    image: saile2204/autoproxy-ddns-updater:latest
    environment:
      GRPC_HOST: "hostmanager-server-1"
    tty: true
    depends_on:
      - server
    networks:
      - internal
  
  port-manager:
    build:
      context: .
      dockerfile: ./AutoProxy.PortManager/Dockerfile
    image: saile2204/autoproxy-portsync:latest
    environment:
      GRPC_HOST: "hostmanager-server-1"
    tty: true
    depends_on:
      - server
    networks:
      - internal
    


