version: "3.9"

networks:
  internal:

services: 
  server:
    build:
      context: .
      dockerfile: ./AutoProxy.Server/Dockerfile
    image: saile2204/autoproxy-server:latest
    tty: true
    networks:
      - internal
  
  ddns-updater:
    build:
      context: .
      dockerfile: ./AutoProxy.DdnsUpdater/Dockerfile
    image: saile2204/autoproxy-ddns-updater:latest
    environment:
      GRPC_HOST: "hostmanager-server-1"
    tty: true
    depends_on:
      - server
    networks:
      - internal
  
  port-manager:
    build:
      context: .
      dockerfile: ./AutoProxy.PortManager/Dockerfile
    image: saile2204/autoproxy-portsync:latest
    environment:
      GRPC_HOST: "hostmanager-server-1"
    tty: true
    depends_on:
      - server
    networks:
      - internal
    


